volumes:
  mongodata:

services:
  database:
    image: mongo
    command: --logpath /var/log/mongodb/mongod
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
  api:
    build: api
    ports:
      - "8000:8000"
  ui:
    build: ui
    ports:
      - "3000:3000"
    volumes:
      - "./ui:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
