[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
mongodb = "2.2.2"